/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workflowmanagement;

import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hatim
 */
public class PmFrame extends javax.swing.JFrame {

    /**
     * Creates new form PmFrame
     */
    UserInfo info;
    String proj_name;
    WFMdatabase db;
    DefaultTableModel team_model;
    DefaultListModel emp_list;
    public PmFrame(UserInfo info) {
        initComponents();
        this.info = info;
        db = new WFMdatabase(this);
        proj_name = db.get_project_name(info.getUname());
        team_model = (DefaultTableModel) team_table.getModel();
        emp_list = new DefaultListModel();
        set_profile();
        set_team_table();
        set_employee_list();
        project_name.setText(proj_name);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        profile_info = new javax.swing.JPanel();
        first_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        last_name = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        designation = new javax.swing.JLabel();
        project_information = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        project_name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        team_table = new javax.swing.JTable();
        add_team = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        team_title = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        employee_list = new javax.swing.JList();
        done = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Welcome PM");

        first_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first_name.setText("jLabel5");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("First name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Last name");

        last_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        last_name.setText("jLabel5");

        Age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Age.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sex");

        sex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sex.setText("jLabel5");

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Designation");

        designation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        designation.setText("jLabel5");

        javax.swing.GroupLayout profile_infoLayout = new javax.swing.GroupLayout(profile_info);
        profile_info.setLayout(profile_infoLayout);
        profile_infoLayout.setHorizontalGroup(
            profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_infoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(profile_infoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(last_name))
                        .addGroup(profile_infoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(87, 87, 87)
                            .addComponent(first_name)))
                    .addGroup(profile_infoLayout.createSequentialGroup()
                        .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_infoLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(113, 113, 113))
                                .addGroup(profile_infoLayout.createSequentialGroup()
                                    .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(118, 118, 118)))
                            .addGroup(profile_infoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(81, 81, 81)))
                        .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designation)
                            .addComponent(sex)
                            .addComponent(Age)
                            .addComponent(email))))
                .addContainerGap(576, Short.MAX_VALUE))
        );
        profile_infoLayout.setVerticalGroup(
            profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_infoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(first_name))
                .addGap(28, 28, 28)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(last_name))
                .addGap(34, 34, 34)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Age))
                .addGap(29, 29, 29)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sex))
                .addGap(28, 28, 28)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email))
                .addGap(27, 27, 27)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(designation))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Profile", profile_info);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Project name :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Team information");

        team_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team title", "Team leader"
            }
        ));
        jScrollPane1.setViewportView(team_table);

        javax.swing.GroupLayout project_informationLayout = new javax.swing.GroupLayout(project_information);
        project_information.setLayout(project_informationLayout);
        project_informationLayout.setHorizontalGroup(
            project_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(project_informationLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(project_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(project_informationLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(62, 62, 62)
                        .addComponent(project_name, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        project_informationLayout.setVerticalGroup(
            project_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(project_informationLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(project_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(project_name, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Project information", project_information);

        jLabel10.setText("Enter team title : ");

        jLabel11.setText("Appoint a team leader from the following list of employees");

        employee_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(employee_list);

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_teamLayout = new javax.swing.GroupLayout(add_team);
        add_team.setLayout(add_teamLayout);
        add_teamLayout.setHorizontalGroup(
            add_teamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_teamLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(add_teamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(done)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(add_teamLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(91, 91, 91)
                        .addComponent(team_title, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        add_teamLayout.setVerticalGroup(
            add_teamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_teamLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(add_teamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(team_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel11)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(done)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add team", add_team);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
      String tl_title = team_title.getText();
     String tl_name = (String) employee_list.getSelectedValue();   
     db.insert_team_info(proj_name, tl_title, tl_name); 
     JOptionPane.showMessageDialog(this, "Team created successfully !");
     set_team_table();
     set_employee_list();
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public void set_profile(){
        first_name.setText(info.getFirst_name());
        last_name.setText(info.getLast_name());
        Age.setText(String.valueOf(info.getAge()));
        sex.setText(info.getSex());
        email.setText(info.getEmail());
        designation.setText(info.getDesig());
    }

    public void set_team_table(){
       
        ResultSet rs = db.get_team_info(proj_name);
    try{
    team_model.setRowCount(0);
    while(!rs.isAfterLast()){
        
        team_model.addRow(new Object[]{rs.getString(1),rs.getString(2)});
        rs.next();
        
    }
    }
    catch(Exception e){
        
    }
    }
    public void set_employee_list(){
        try{
            emp_list.clear();
             ResultSet rs = db.get_emp_list_no_desig();
             while(!rs.isAfterLast()){
                 emp_list.addElement(rs.getString(1));
                 rs.next();
             }
             employee_list.setModel(emp_list);
         }
         catch(Exception e){
             
         }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JPanel add_team;
    private javax.swing.JLabel designation;
    private javax.swing.JButton done;
    private javax.swing.JLabel email;
    private javax.swing.JList employee_list;
    private javax.swing.JLabel first_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel last_name;
    private javax.swing.JButton logout;
    private javax.swing.JPanel profile_info;
    private javax.swing.JPanel project_information;
    private javax.swing.JLabel project_name;
    private javax.swing.JLabel sex;
    private javax.swing.JTable team_table;
    private javax.swing.JTextField team_title;
    // End of variables declaration//GEN-END:variables
}
