/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workflowmanagement;

import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hatim
 */
public class SmFrame extends javax.swing.JFrame {

    /**
     * Creates new form SmFrame
     */
    UserInfo info;
    WFMdatabase db;
    DefaultTableModel emp_model;
    DefaultTableModel projects_model;
    DefaultListModel emp_list;
    DefaultListModel proj_list;
    String uname;
    String proj_name;
    public SmFrame(UserInfo info) {
        initComponents();
        this.info = info;
        db = new WFMdatabase(this);
        emp_model = (DefaultTableModel) employee_table.getModel();
        projects_model = (DefaultTableModel) projects_table.getModel();
        emp_list = new DefaultListModel();
        proj_list = new DefaultListModel();
        projlist_title.setVisible(false);
        done.setVisible(false);
        projects_list.setVisible(false);
        set_profile();
        set_project_details();
        set_employee_details();
        set_emp_list();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        profile_info = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        first_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        last_name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        designation = new javax.swing.JLabel();
        project_details = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        projects_table = new javax.swing.JTable();
        employee_details = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        employee_table = new javax.swing.JTable();
        appoint_pm = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        employee_list = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        projlist_title = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        projects_list = new javax.swing.JList();
        appoint = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("First name");

        first_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        first_name.setText("jLabel5");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Last name");

        last_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        last_name.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        Age.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Age.setText("jLabel5");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sex");

        sex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sex.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email");

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setText("jLabel5");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Designation");

        designation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        designation.setText("jLabel5");

        javax.swing.GroupLayout profile_infoLayout = new javax.swing.GroupLayout(profile_info);
        profile_info.setLayout(profile_infoLayout);
        profile_infoLayout.setHorizontalGroup(
            profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_infoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(profile_infoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(last_name))
                        .addGroup(profile_infoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(87, 87, 87)
                            .addComponent(first_name)))
                    .addGroup(profile_infoLayout.createSequentialGroup()
                        .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profile_infoLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(113, 113, 113))
                                .addGroup(profile_infoLayout.createSequentialGroup()
                                    .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(118, 118, 118)))
                            .addGroup(profile_infoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(81, 81, 81)))
                        .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designation)
                            .addComponent(sex)
                            .addComponent(Age)
                            .addComponent(email))))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        profile_infoLayout.setVerticalGroup(
            profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_infoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(first_name))
                .addGap(28, 28, 28)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(last_name))
                .addGap(34, 34, 34)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Age))
                .addGap(29, 29, 29)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sex))
                .addGap(28, 28, 28)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email))
                .addGap(27, 27, 27)
                .addGroup(profile_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(designation))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Profile", profile_info);

        projects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project name", "Project manager"
            }
        ));
        jScrollPane4.setViewportView(projects_table);

        javax.swing.GroupLayout project_detailsLayout = new javax.swing.GroupLayout(project_details);
        project_details.setLayout(project_detailsLayout);
        project_detailsLayout.setHorizontalGroup(
            project_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(project_detailsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        project_detailsLayout.setVerticalGroup(
            project_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, project_detailsLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Project Details", project_details);

        employee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee name", "Designation"
            }
        ));
        jScrollPane8.setViewportView(employee_table);

        javax.swing.GroupLayout employee_detailsLayout = new javax.swing.GroupLayout(employee_details);
        employee_details.setLayout(employee_detailsLayout);
        employee_detailsLayout.setHorizontalGroup(
            employee_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employee_detailsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        employee_detailsLayout.setVerticalGroup(
            employee_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employee_detailsLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        jTabbedPane1.addTab("Employee details", employee_details);

        employee_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(employee_list);

        jLabel13.setText("Select from the following list of employees");

        projlist_title.setText("Select project to be assigned ");

        projects_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(projects_list);

        appoint.setText("Appoint");
        appoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointActionPerformed(evt);
            }
        });

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appoint_pmLayout = new javax.swing.GroupLayout(appoint_pm);
        appoint_pm.setLayout(appoint_pmLayout);
        appoint_pmLayout.setHorizontalGroup(
            appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appoint_pmLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appoint))
                .addGap(110, 110, 110)
                .addGroup(appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(done)
                    .addGroup(appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane7)
                        .addComponent(projlist_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        appoint_pmLayout.setVerticalGroup(
            appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appoint_pmLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(projlist_title))
                .addGap(60, 60, 60)
                .addGroup(appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addGap(43, 43, 43)
                .addGroup(appoint_pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appoint)
                    .addComponent(done))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Appoint PM", appoint_pm);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Welcome SM");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logout)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(logout)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
      new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void appointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointActionPerformed
        uname = (String) employee_list.getSelectedValue();
        display_proj_list();
    }//GEN-LAST:event_appointActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
      proj_name = (String) projects_list.getSelectedValue();
      db.update_proj_manager(proj_name, uname);
        projlist_title.setVisible(false);
        done.setVisible(false);
        projects_list.setVisible(false);
        set_emp_list();
        set_project_details();
        set_employee_details();
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */

    public void set_profile(){
        first_name.setText(info.getFirst_name());
        last_name.setText(info.getLast_name());
        Age.setText(String.valueOf(info.getAge()));
        sex.setText(info.getSex());
        email.setText(info.getEmail());
        designation.setText(info.getDesig());
    }
    
      
    public void set_project_details(){
    ResultSet rs = db.get_project_info();
    try{
    projects_model.setRowCount(0);
    while(!rs.isAfterLast()){
      
        if(rs.getString(2).equals(""))
             projects_model.addRow(new Object[]{rs.getString(1),"Not appointed"});
        else 
             projects_model.addRow(new Object[]{rs.getString(1),rs.getString(2)});
        rs.next();
    }
    }
    catch(Exception e){
        
    }
    }
     public void set_employee_details(){
         
         try{
            emp_model.setRowCount(0);
             ResultSet rs = db.get_emp_list();
             while(!rs.isAfterLast()){
                 if(rs.getString(3).equals(""))
                       emp_model.addRow(new Object[]{rs.getString(1)+ " "+rs.getString(2), "Not Appointed"});
                 else
                       emp_model.addRow(new Object[]{rs.getString(1)+ " "+rs.getString(2), rs.getString(3)});
                 rs.next();
             }
         }
         catch(Exception e){
             
         }
     }
     
     public void set_emp_list(){
         
      
        try{
            emp_list.clear();
             ResultSet rs = db.get_emp_list_no_desig();
             while(!rs.isAfterLast()){
                 emp_list.addElement(rs.getString(1));
                 rs.next();
             }
             employee_list.setModel(emp_list);
         }
         catch(Exception e){
             
         }
     }
     
     public void display_proj_list(){
       projlist_title.setVisible(true);
       done.setVisible(true);
       projects_list.setVisible(true);
       
        try{
            proj_list.clear();
             ResultSet rs = db.get_project_info_nopm();
             while(!rs.isAfterLast()){
                 proj_list.addElement(rs.getString(1));
                 rs.next();
             }
             projects_list.setModel(proj_list);
         }
         catch(Exception e){
             
         }
        
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JButton appoint;
    private javax.swing.JPanel appoint_pm;
    private javax.swing.JLabel designation;
    private javax.swing.JButton done;
    private javax.swing.JLabel email;
    private javax.swing.JPanel employee_details;
    private javax.swing.JList employee_list;
    private javax.swing.JTable employee_table;
    private javax.swing.JLabel first_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel last_name;
    private javax.swing.JButton logout;
    private javax.swing.JPanel profile_info;
    private javax.swing.JPanel project_details;
    private javax.swing.JList projects_list;
    private javax.swing.JTable projects_table;
    private javax.swing.JLabel projlist_title;
    private javax.swing.JLabel sex;
    // End of variables declaration//GEN-END:variables
}
